server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: view_world
    password: RD6bMXcSsGZpxArt
    url: jdbc:mysql://101.37.20.150:3306/view_world?&useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC